name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  NODE_VERSION: 24

jobs:
  playwright-tests:
    timeout-minutes: 60
    name: ${{ matrix.os }}-${{ matrix.env_type }}-${{ matrix.project }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        env_type: [local, docker]
        project: [chromium, firefox]
        include:
          - os: macos-12
            env_type: local
            project: chromium
          - os: macos-12
            env_type: local
            project: firefox
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Install Playwright browser
        if: matrix.env_type == 'local'
        run: node node_modules/.bin/playwright install ${{ matrix.project }}
      - name: Run server
        run: node server.js &
      - name: Run Playwright tests
        run: |
          if [ "${{ matrix.env_type }}" == "local" ]; then
            /bin/bash playwright.sh -t local --headless --project ${{ matrix.project }}
          else
            /bin/bash playwright.sh -t docker --project ${{ matrix.project }}
          fi

# https://playwright.dev/docs/ci
