name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-20.04 # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.11.0'
    - name: yarn install
      run: yarn
    - name: install chromium
      run: npx playwright install chromium
    - name: playwright tests
      run: |
        npx playwright test --headed --forbid-only --project=chromium --workers=1